--INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (11, 11.01);
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (15, 15.01, 'toan');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (12, 12.01, 'toan');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (13, 13.01, 'amee');